---
server:
    port: 8888
security:
   basic:
      enabled: true # if set to false, bypasses basic auth
   user: # optional if you add here, you need to use basic auth with these.
     name: pluralsight
     password: pluralsight
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spurcell999/pluralsight-spring-cloudconfig-wa-tolls.git
          search-paths:
          - 'station*'
          repos:
             perf:
                 pattern:
                      -"*/perf"
                 uri: https://github.com/rseroter/pluralsight-spring-cloudconfig-wa-tolls-perf.git
                 search-paths:
                 - 'station*'
          #username: uname
          #password: pass